[package]
name = "deque"
version = "0.1.0"
authors = ["kamil <gryxon@gmail.com>"]
edition = "2018"

[lib]
name = "deque"
path = "src/lib.rs"

[[bin]]
name = "deque"
path = "src/main.rs"

[dependencies]
